# Generated by Django 5.0.1 on 2024-01-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
