# Generated by Django 5.0.1 on 2024-03-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0004_alter_result_price_alter_result_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChocolateProduct',
        ),
    ]
