# Generated by Django 5.0.3 on 2024-03-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0007_question_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('sector', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('num_posts', models.IntegerField()),
                ('url_posts', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
