# Generated by Django 5.0.3 on 2024-03-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0008_company_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='num_posts',
            field=models.CharField(max_length=255),
        ),
    ]
