# Generated by Django 5.0.3 on 2024-03-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0009_alter_company_num_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('commentaire', models.TextField()),
                ('secteur_activite', models.TextField(db_column="Secteur d'activité")),
                ('localisation', models.TextField()),
                ('nombre_de_postes', models.TextField(db_column='Nombre de postes')),
                ('url_postes', models.TextField()),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
