# Generated by Django 5.0.3 on 2024-03-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0010_infos_delete_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='infos',
            table=None,
        ),
    ]
