# Generated by Django 5.0.3 on 2024-03-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0011_alter_infos_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infos',
            new_name='Companies',
        ),
    ]
