# Generated by Django 5.0.3 on 2024-03-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0012_rename_infos_companies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
