# Generated by Django 5.0.3 on 2024-03-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0013_delete_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('secteur_activite', models.CharField(blank=True, max_length=255, verbose_name="Secteur d'activité")),
                ('localisation', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('nombre_de_postes', models.CharField(blank=True, max_length=255, verbose_name='Nombre de postes')),
                ('url_postes', models.URLField(blank=True, max_length=255, verbose_name='URL Postes')),
            ],
        ),
    ]
