# Generated by Django 5.0.3 on 2024-03-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0014_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Infos',
        ),
    ]
