# Generated by Django 5.0.3 on 2024-03-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0015_rename_company_infos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infos',
            new_name='Company',
        ),
    ]
