# Generated by Django 5.0.3 on 2024-03-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0018_company_delete_compagnies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='comment',
        ),
    ]
