# Generated by Django 5.0.3 on 2024-03-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0019_remove_company_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.TextField(verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='num_posts',
            field=models.TextField(verbose_name='Number of Posts'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.TextField(verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='company',
            name='url_posts',
            field=models.TextField(verbose_name='URL Posts'),
        ),
    ]
