# Generated by Django 5.0.3 on 2024-03-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0022_rename_price_chaussure_price_cfa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaussure',
            name='price_cfa',
        ),
        migrations.AddField(
            model_name='chaussure',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
