# Generated by Django 5.0.3 on 2024-03-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0023_remove_chaussure_price_cfa_chaussure_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaussure',
            old_name='price',
            new_name='price_cfa',
        ),
    ]
